clc; clear all; close all;

% Plot file
file = "BASIC_INPUT@Input[P8_42] Plot.csv";

% Load data from .csv plot file generated by Wearable Software Interface
data = csvread(file, 1, 0);
fprintf("Read File: '%s'\n", file);

% Convert unix timestamps to milliseconds normalized to first row equal 0
timeZero = uint64(data(1,1) * 1000);
data(1,1) = 0;
for i = 2:size(data, 1)
    data(i,1) = uint64(data(i,1) * 1000) - timeZero;
end

% Plot all data sets
legendInfo = {};
for i = 2:size(data, 2)
    plot(data(:, 1), data(:, i)); hold on;
    legendInfo{i-1} = ['Dimension: ' num2str(i-1)];
end

% Cosmetics
legend(legendInfo)
ylabel("Measured Values") 
xlabel("Time [milliseconds]") 
title(sprintf("Line Plot of: '%s'", file))
